### ISSUE TITLE
Doesn't work in PowerShell

### ISSUE THREAD

**Issue by Klaster1** [Qard/onchange#122]
Using the onchange 7.1.0 on Windows 10.

This works in cmd:
```
onchange "**/*" -- echo 1
1
```

But this doesn't in PowerShell 7.2.1:
```
onchange '**/*' -- echo 1
'**\*' is not recognized as an internal or external command,
operable program or batch file.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn **/* ENOENT
    at notFoundError (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn **/*',
  path: '**/*',
  spawnargs: [ 'echo', '1' ]
}
```
this doesn't either:
```
 onchange "**/*" -- echo 1
'**\*' is not recognized as an internal or external command,
operable program or batch file.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn **/* ENOENT
    at notFoundError (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\iborisov\AppData\Roaming\npm\node_modules\onchange\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn **/*',
  path: '**/*',
  spawnargs: [ 'echo', '1' ]
}
```
In each sample, after calling `onchange`, a file is changed to trigger the `echo`. If I'm doing something wrong, then what exactly?

**Comment by rizchaerul** [comment]
Have you tried this? `onchange \"**/*\" -- echo 1`

**Comment by Klaster1** [comment]
@rizchaerul doesn't work either:
```
PS C:\dev\timer-5> onchange \"**/*\" -- echo 1
undefined:3
return (function template(data) { return "\**/*\"; });
                                         ^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at Object.template (C:\Users\Klaster_1\AppData\Roaming\npm\node_modules\onchange\node_modules\@blakeembrey\template\dist\index.js:21:12)
    at C:\Users\Klaster_1\AppData\Roaming\npm\node_modules\onchange\dist\index.js:91:51
    at Array.map (<anonymous>)
    at Object.onchange (C:\Users\Klaster_1\AppData\Roaming\npm\node_modules\onchange\dist\index.js:91:27)
    at Object.<anonymous> (C:\Users\Klaster_1\AppData\Roaming\npm\node_modules\onchange\dist\bin.js:68:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by rizchaerul** [comment]
I see, I guess we can't do that directly from terminal, only from package.json.

```
  "scripts": {
    "watch": "onchange \"**/*\" -- echo 1"
  },

  // Or without the quote
  "scripts": {
    "watch": "onchange **/* -- echo 1"
  },
```

I tested it using npm run watch and it worked.

**Comment by Klaster1** [comment]
Running it with `npm run` does work. Maybe consider updating project readme?

**Comment by blakeembrey** [comment]
@Klaster1 You're welcome to update the project README using a PR. I'm going to close out this issue since it seems to be resolved, and the resolution appears to be that you can't use single quotes in PowerShell. I've never used PowerShell to confirm how the shell works but if double quotes usually work you can just use them. There's nothing saying you need to use single or double quotes, it depends on how your shell interprets them. In bash the double quotes may have interpolation while single quotes are just literals arguments.

**Comment by blakeembrey** [comment]
I'm a little confused too because PowerShell docs mention they work the same way: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2&viewFallbackFrom=powershell-6.
