### ISSUE TITLE
Outpipe opts not defined

### ISSUE THREAD

**Issue by betsu** [Qard/onchange#75]
There is my code:
``` 
onchange "**/*/*.scss" "**/*/*.css" -o "> task/css.txt" -- echo {{changed}}
```

in v4.0.0 is working, but in v5.0.0 still error
```
const cmd = this.outpipe(opts)
                         ^

ReferenceError: opts is not defined
    at Job.start (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\onchange\index.js:29:32)
    at dequeue (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\onchange\index.js:131:10)
    at enqueue (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\onchange\index.js:155:12)
    at FSWatcher.watcher.on (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\onchange\index.js:168:14)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.<anonymous> (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\chokidar\index.js:200:38)
    at FSWatcher._emit (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\chokidar\index.js:241:5)
    at FSWatcher.<anonymous> (E:\Snow.Huang\project\dev\CampaignBuildTool\node_modules\chokidar\lib\nodefs-handler.js:267:16)
    at FSReqWrap.oncomplete (fs.js:155:5)
```

**Comment by blakeembrey** [comment]
Thanks for the report! Should be fixed with the next release.
